spring:
  datasource:
    username: root
    password: yfy57320
    url: jdbc:mysql://localhost:3306/paint?useUnicode=true&amp
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.paint.demo.pojo
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8080